---
# This playbook deploys the whole application stack in this site.  

# Make sure the facts of all servers are available for the role to be applied
- hosts: all
  tasks: []

# Configure and deploy the web servers. 
- hosts: webservers
  sudo: True
  roles:
  - web_rolling_update
